spring:
  datasource:
    url: jdbc:h2:mem:poupei
    username: poupei
    password: poupei@01
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true