app:
  auth:
    shared-secret: ${SERVICE_SHARED_SECRET}

spring:
  security:
    user:
      name: name
      password: password
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: ${DATABASE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT}
        format_sql: ${DATABASE_FORMAT_SQL}
    show-sql: ${DATABASE_SHOW_SQL}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /docs
    url: /api-docs.yaml
    disable-swagger-default-url: true