spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poupei
    username: root
    password: 3.1415926535yan
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: valid

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation:
    show-sql: true
